# Generated by Django 2.0.7 on 2018-07-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
