# Generated by Django 2.0.7 on 2018-07-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_meta_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
