# Generated by Django 2.1 on 2018-08-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('began', models.DateTimeField(help_text='When the load attempt began.', null=True)),
                ('finished', models.DateTimeField(help_text='When the load attempt finished.', null=True)),
                ('update_calaccess_began', models.DateTimeField(help_text='When `updatecalaccess` command began.', null=True)),
                ('update_calaccess_finished', models.DateTimeField(help_text='When `updatecalaccess` command finished.', null=True)),
                ('load_activities_began', models.DateTimeField(help_text='When `loadactivities` command began.', null=True)),
                ('load_activities_finished', models.DateTimeField(help_text='When `loadactivities` command finished.', null=True)),
                ('load_bills_began', models.DateTimeField(help_text='When `loadbills` command began.', null=True)),
                ('load_bills_finished', models.DateTimeField(help_text='When `loadbills` command finished.', null=True)),
                ('connect_bills_began', models.DateTimeField(help_text='When `connectbills` command began.', null=True)),
                ('connect_bills_finished', models.DateTimeField(help_text='When `connectbills` command finished.', null=True)),
            ],
        ),
    ]
