# Generated by Django 2.0.7 on 2018-07-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_id', models.IntegerField(db_column='filing_id', db_index=True)),
                ('amendment_id', models.IntegerField(db_column='amendment_id', db_index=True)),
                ('transaction_id', models.CharField(blank=True, db_column='transaction_id', max_length=20, null=True)),
                ('form_type', models.CharField(blank=True, choices=[('F625', 'F625'), ('F635', 'F635')], db_column='form_type', max_length=4, null=True)),
                ('entity_code', models.CharField(blank=True, choices=[('LEM', 'Lobby Employer'), ('FRM', 'Lobby Firm')], db_column='entity_code', max_length=4, null=True)),
                ('filing_date', models.DateField(db_column='filing_date', null=True)),
                ('filer_id', models.CharField(blank=True, db_column='filer_id', max_length=9, null=True)),
                ('filer_name', models.CharField(blank=True, db_column='filer_name', max_length=250, null=True)),
                ('filer_last_name', models.CharField(blank=True, db_column='filer_last_name', max_length=200, null=True)),
                ('filer_first_name', models.CharField(blank=True, db_column='filer_first_name', max_length=45, null=True)),
                ('lobbyer_id', models.CharField(blank=True, db_column='lobbyer_id', max_length=9, null=True)),
                ('lobbyer_name', models.CharField(blank=True, db_column='lobbyer_name', max_length=250, null=True)),
                ('lobbyer_last_name', models.CharField(blank=True, db_column='lobbyer_last_name', max_length=200, null=True)),
                ('lobbyer_first_name', models.CharField(blank=True, db_column='lobbyer_first_name', max_length=45, null=True)),
                ('lobbyer_city', models.CharField(blank=True, db_column='lobbyer_city', max_length=30, null=True)),
                ('lobbyer_state', models.CharField(blank=True, db_column='lobbyer_state', max_length=2, null=True)),
                ('lobbyer_zip', models.CharField(blank=True, db_column='lobbyer_zip', max_length=10, null=True)),
                ('lobbyer_phone', models.CharField(blank=True, db_column='lobbyer_phone', max_length=20, null=True)),
                ('employer_id', models.CharField(blank=True, db_column='employer_id', max_length=9, null=True)),
                ('employer_name', models.CharField(blank=True, db_column='employer_name', max_length=250, null=True)),
                ('employer_last_name', models.CharField(blank=True, db_column='employer_last_name', max_length=200, null=True)),
                ('employer_first_name', models.CharField(blank=True, db_column='employer_first_name', max_length=45, null=True)),
                ('employer_city', models.CharField(blank=True, db_column='employer_city', max_length=30, null=True)),
                ('employer_state', models.CharField(blank=True, db_column='employer_state', max_length=2, null=True)),
                ('employer_zip', models.CharField(blank=True, db_column='employer_zip', max_length=10, null=True)),
                ('employer_phone', models.CharField(blank=True, db_column='employer_phone', max_length=20, null=True)),
                ('start_date', models.DateField(db_column='start_date', null=True)),
                ('end_date', models.DateField(db_column='end_date', null=True)),
                ('interests', models.CharField(blank=True, db_column='interests', max_length=400, null=True)),
                ('compensation', models.DecimalField(db_column='compensation', decimal_places=2, max_digits=14, null=True)),
                ('reimbursement', models.DecimalField(db_column='reimbursement', decimal_places=2, max_digits=14, null=True)),
                ('period_total', models.DecimalField(db_column='period_total', decimal_places=2, max_digits=14, null=True)),
                ('session_total', models.DecimalField(db_column='session_total', decimal_places=2, max_digits=14, null=True)),
                ('involved_entities', models.CharField(blank=True, db_column='involved_entities', max_length=500, null=True)),
            ],
            options={
                'ordering': ('-filing_id', '-amendment_id'),
            },
        ),
    ]
