# Generated by Django 2.0.7 on 2018-07-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbysearch', '0001_create_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(blank=True, choices=[('inhouse', 'In-house Lobbying'), ('firm', 'Contracted Lobby Firm'), ('pti', 'Payments to Influence')], db_column='type', max_length=10, null=True),
        ),
    ]
