# Generated by Django 2.0.7 on 2018-07-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0002_activity_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('-filing_id', '-amendment_id', 'type', '-period_total')},
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(blank=True, choices=[('inhouse', 'In-house Lobbying'), ('firm', 'Contracted Lobby Firm'), ('other', 'Other Payments to Influence')], db_column='type', max_length=10, null=True),
        ),
    ]
