# Generated by Django 2.0.7 on 2018-07-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_normalized_field'),
        ('lobbying', '0003_update_activity_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='bills',
            field=models.ManyToManyField(blank=True, related_name='activities', to='bills.Bill'),
        ),
    ]
