# Generated by Django 2.1 on 2018-11-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbying', '0004_activities_bills_m2m'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('-filing_id', 'employer_name', 'lobbyer_name'), 'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='activity',
            name='involved_keywords',
            field=models.TextField(blank=True, db_column='involved_keywords', null=True),
        ),
    ]
